name: Renovate Bot

on:
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch: 

permissions:
  contents: write
  pull-requests: write
jobs:
  renovate:
    uses: prom-candp/platform-gh-workflows/.github/workflows/bot-renovate.yaml@workflows-v2.12.1
    with:
      app-id: ${{ vars.CANDP_RENOVATEBOT_APP_ID }}
    secrets:
      private-key: ${{ secrets.CANDP_RENOVATEBOT_PRIVATE_KEY }}
